
export type Property = {
  id: string;
  title: string;
  price: number;
  images: string[];
  location: string;
  refNumber: string;
  bedrooms: number;
  bathrooms: number;
  description: string;
  m2: number;
  town: string;
  area: string;
  propertyType: 'Villa' | 'Apartment' | 'Townhouse' | 'Penthouse';
  plotSize: number;
  buildYear: number;
  terrace: boolean;
  aiHints: string[];
  priceType?: 'exact' | 'from';
};

export const properties: Property[] = [
  {
    id: '1',
    title: 'Luxurious Villa with Ocean View',
    price: 2500000,
    images: ['https://fotos15.apinmo.com/7515/26122500/9-1.jpg', 'https://fotos15.apinmo.com/7515/26122500/9-2.jpg', 'https://fotos15.apinmo.com/7515/26122500/9-3.jpg'],
    location: 'Marbella, Golden Mile',
    refNumber: 'EE-001',
    bedrooms: 5,
    bathrooms: 6,
    description: 'A stunning modern villa located on the prestigious Golden Mile of Marbella. This property boasts panoramic sea views, a private infinity pool, and state-of-the-art home automation. The open-plan living space is perfect for entertaining, with floor-to-ceiling windows that flood the interior with natural light.',
    m2: 650,
    town: 'Marbella',
    area: 'Golden Mile',
    propertyType: 'Villa',
    plotSize: 1500,
    buildYear: 2022,
    terrace: true,
    aiHints: ['luxury villa', 'ocean view'],
    priceType: 'from',
  },
  {
    id: '2',
    title: 'Modern Apartment in the City Center',
    price: 850000,
    images: ['https://appropertiesspain.com/media/images/properties/o_1j0m7j87d19ud4vqbjl11091fse1q.jpg', 'https://appropertiesspain.com/media/images/properties/o_1j0m7j87dmq51mk4h3k8tadit1l.jpg'],
    location: 'Malaga, Centro Histórico',
    refNumber: 'EE-002',
    bedrooms: 3,
    bathrooms: 2,
    description: 'Chic and stylish apartment in the heart of Malaga\'s historic center. Fully renovated with high-end finishes, this property is steps away from museums, restaurants, and shops. Features a spacious living area and a private balcony overlooking the vibrant city streets.',
    m2: 180,
    town: 'Malaga',
    area: 'Centro Histórico',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2020,
    terrace: true,
    aiHints: ['modern apartment', 'city center'],
  },
  {
    id: '3',
    title: 'Charming Townhouse in a Gated Community',
    price: 650000,
    images: ['https://casas-connect.es/media/images/properties/o_1j0a6kpkc1sjuktsj1uu90tv437.jpg'],
    location: 'Estepona, New Golden Mile',
    refNumber: 'EE-003',
    bedrooms: 4,
    bathrooms: 3,
    description: 'A beautiful townhouse in a quiet, family-friendly gated community. The property includes a private garden, access to a communal pool, and is just a short walk from the beach. Perfect for families or as a holiday home.',
    m2: 220,
    town: 'Estepona',
    area: 'New Golden Mile',
    propertyType: 'Townhouse',
    plotSize: 300,
    buildYear: 2018,
    terrace: true,
    aiHints: ['charming townhouse', 'gated community'],
  },
  {
    id: '4',
    title: 'Exclusive Penthouse with Rooftop Terrace',
    price: 3200000,
    images: ['https://assetsrv.advanceagent.co.uk/1240/5b1d/3307de66/IMG_7826_xlarge.jpeg', 'https://assetsrv.advanceagent.co.uk/1240/5b1d/50323d3b/IMG_7819_xlarge.jpeg', 'https://assetsrv.advanceagent.co.uk/1240/5b1d/d3cfc79d/IMG_7825_xlarge.jpeg'],
    location: 'Benahavís, La Zagaleta',
    refNumber: 'EE-004',
    bedrooms: 4,
    bathrooms: 5,
    description: 'An exquisite penthouse offering the ultimate in luxury living. The highlight is the expansive rooftop terrace with a private plunge pool, outdoor kitchen, and breathtaking 360-degree views of the mountains and the Mediterranean Sea.',
    m2: 450,
    town: 'Benahavís',
    area: 'La Zagaleta',
    propertyType: 'Penthouse',
    plotSize: 0,
    buildYear: 2021,
    terrace: true,
    aiHints: ['exclusive penthouse', 'rooftop terrace'],
  },
   {
    id: '5',
    title: 'Contemporary Villa in a Golf Resort',
    price: 1800000,
    images: ['https://fotos15.apinmo.com/7515/25946560/10-1.jpg', 'https://fotos15.apinmo.com/7515/25946560/10-2.jpg', 'https://fotos15.apinmo.com/7515/25946560/10-3.jpg'],
    location: 'Mijas, La Cala Golf',
    refNumber: 'EE-005',
    bedrooms: 4,
    bathrooms: 4,
    description: 'Sleek and modern villa located within a prestigious golf resort. This property features clean lines, open spaces, and high-quality materials. Enjoy the tranquility and stunning views of the golf course from your private terrace and pool.',
    m2: 500,
    town: 'Mijas',
    area: 'La Cala Golf',
    propertyType: 'Villa',
    plotSize: 1200,
    buildYear: 2023,
    terrace: true,
    aiHints: ['contemporary villa', 'golf resort'],
    priceType: 'from',
  },
  {
    id: '6',
    title: 'Beachfront Apartment with Direct Access',
    price: 1100000,
    images: ['https://respacio-4c53102df1c9de6eca4f00689a84fb6b.s3.eu-west-3.amazonaws.com/property_attachment/detail_image/property_attachment_1xzmivzpae_20250715022853.jpg', 'https://respacio-4c53102df1c9de6eca4f00689a84fb6b.s3.eu-west-3.amazonaws.com/property_attachment/detail_image/property_attachment_1wuxmo2csd_20250715022850.jpg'],
    location: 'Fuengirola, Los Boliches',
    refNumber: 'EE-006',
    bedrooms: 2,
    bathrooms: 2,
    description: 'A rare opportunity to own a frontline beach apartment with direct access to the sand. Wake up to the sound of the waves and enjoy stunning sunrises from your private balcony. The community offers a large swimming pool and well-maintained gardens.',
    m2: 150,
    town: 'Fuengirola',
    area: 'Los Boliches',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2015,
    terrace: true,
    aiHints: ['beachfront apartment', 'sea view'],
  },
  {
    id: '7',
    title: 'Modern Townhouse with Solarium',
    price: 750000,
    images: ['https://images.optima-crm.com//resize/commercial_images/669a7961ecf2a162ffbaf204/1200/20240726130832000000_DSC08433.jpg'],
    location: 'San Pedro de Alcántara',
    refNumber: 'EE-007',
    bedrooms: 3,
    bathrooms: 3,
    description: 'Brand new townhouse in a contemporary development. Features a spacious solarium with a jacuzzi, perfect for enjoying the Spanish sun. Located close to the town center and a short drive to Puerto Banús.',
    m2: 190,
    town: 'San Pedro',
    area: 'Centro',
    propertyType: 'Townhouse',
    plotSize: 150,
    buildYear: 2024,
    terrace: true,
    aiHints: ['modern townhouse', 'solarium'],
    priceType: 'from',
  },
  {
    id: '8',
    title: 'Luxury Villa with Sea View',
    price: 2800000,
    images: ['https://images.optima-crm.com//resize/commercial_images/6756e5cf8ca4935595176cca/1200/20241211085251000000_027B8986D.jpg', 'https://images.optima-crm.com//resize/commercial_images/6756e5cf8ca4935595176cca/1200/20241211085251000000_003B8986D.jpg', 'https://images.optima-crm.com//resize/commercial_images/6756e5cf8ca4935595176cca/1200/20241211085251000000_000B8986D.jpg'],
    location: 'Marbella, Sierra Blanca',
    refNumber: 'EE-008',
    bedrooms: 6,
    bathrooms: 7,
    description: 'An imposing villa in the sought-after Sierra Blanca urbanisation, offering breathtaking sea views. This property combines classic Andalusian architecture with modern luxury, featuring a home cinema, gym, and a large tropical garden.',
    m2: 800,
    town: 'Marbella',
    area: 'Sierra Blanca',
    propertyType: 'Villa',
    plotSize: 2000,
    buildYear: 2019,
    terrace: true,
    aiHints: ['luxury villa', 'sea view'],
  },
  {
    id: '9',
    title: 'Garden Apartment in Benalmadena',
    price: 550000,
    images: ['https://members.alphashare.com/photos/full_1466645_64855933.jpg', 'https://members.alphashare.com/photos/full_1466645_64855931.jpg'],
    location: 'Benalmadena, Torrequebrada',
    refNumber: 'EE-009',
    bedrooms: 2,
    bathrooms: 2,
    description: 'Spacious ground floor apartment with a large private garden, ideal for outdoor living. The complex is well-maintained and offers several pools and 24-hour security. Close to the beach, golf, and all amenities.',
    m2: 130,
    town: 'Benalmadena',
    area: 'Torrequebrada',
    propertyType: 'Apartment',
    plotSize: 200,
    buildYear: 2017,
    terrace: true,
    aiHints: ['garden apartment', 'community pool'],
  },
  {
    id: '10',
    title: 'Family Townhouse near Puerto Banus',
    price: 950000,
    images: ['https://www.robertoproperties.com/sites/001/images/24344-for-sale-in-villamartin/24344-for-sale-in-villamartin-15444285-large.jpg'],
    location: 'Marbella, Nueva Andalucía',
    refNumber: 'EE-010',
    bedrooms: 4,
    bathrooms: 4,
    description: 'A spacious and bright townhouse located in the heart of the Golf Valley, just a few minutes drive from Puerto Banús. The property has been recently refurbished and offers a modern open-plan kitchen, a cozy fireplace, and multiple terraces.',
    m2: 280,
    town: 'Marbella',
    area: 'Nueva Andalucía',
    propertyType: 'Townhouse',
    plotSize: 400,
    buildYear: 2015,
    terrace: true,
    aiHints: ['family townhouse', 'golf valley'],
  },
  {
    id: '11',
    title: 'Penthouse with Panoramic Views',
    price: 1500000,
    images: ['https://images.optima-crm.com//resize/commercial_images/667ad8e535c5a871308ceeda/1200/20240625165103000000_villa-moderna-en-residencial-lirios-cumbre-del-sol-1586-76.jpg', 'https://images.optima-crm.com//resize/commercial_images/667ad8e535c5a871308ceeda/1200/20240625165102000000_villa-moderna-en-residencial-lirios-cumbre-del-sol-1586-75.jpg'],
    location: 'Estepona, Town Center',
    refNumber: 'EE-011',
    bedrooms: 3,
    bathrooms: 3,
    description: 'Unique duplex penthouse in the center of Estepona, offering panoramic views over the town, the sea, and the mountains. This property features a large terrace with a private pool and is within walking distance to all amenities.',
    m2: 250,
    town: 'Estepona',
    area: 'Centro',
    propertyType: 'Penthouse',
    plotSize: 0,
    buildYear: 2022,
    terrace: true,
    aiHints: ['duplex penthouse', 'panoramic views'],
    priceType: 'from'
  },
  {
    id: '12',
    title: 'Andalusian Cortijo in Mijas',
    price: 2100000,
    images: ['https://www.thepropertyteam.es/sites/001/images/11799-country-house-for-sale-in-jalon/11799-country-house-for-sale-in-jalon-248768-large.jpg', 'https://www.thepropertyteam.es/sites/001/images/11799-country-house-for-sale-in-jalon/11799-country-house-for-sale-in-jalon-248559-large.jpg', 'https://www.thepropertyteam.es/sites/001/images/11799-country-house-for-sale-in-jalon/11799-country-house-for-sale-in-jalon-248577-large.jpg'],
    location: 'Mijas, Campo',
    refNumber: 'EE-012',
    bedrooms: 7,
    bathrooms: 6,
    description: 'A stunning Andalusian cortijo set in a large private estate, offering complete privacy and tranquility. The property has been beautifully restored, preserving many original features. It includes a guest house, stables, and a mature garden.',
    m2: 900,
    town: 'Mijas',
    area: 'Campo',
    propertyType: 'Villa',
    plotSize: 10000,
    buildYear: 2005,
    terrace: true,
    aiHints: ['andalusian cortijo', 'private estate'],
  },
  {
    id: '13',
    title: 'Frontline Golf Apartment',
    price: 480000,
    images: ['https://fotos15.apinmo.com/6255/24035799/6-1.jpg'],
    location: 'Marbella, Cabopino',
    refNumber: 'EE-013',
    bedrooms: 2,
    bathrooms: 2,
    description: 'Bright and modern apartment located in a frontline golf complex in Cabopino. The property enjoys beautiful views over the golf course and has a large, sunny terrace. The port of Cabopino with its lovely beaches and restaurants is only a short walk away.',
    m2: 110,
    town: 'Marbella',
    area: 'Cabopino',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2019,
    terrace: true,
    aiHints: ['frontline golf', 'modern apartment'],
  },
  {
    id: '14',
    title: 'Renovated Townhouse in Old Town',
    price: 895000,
    images: ['https://respacio-4c53102df1c9de6eca4f00689a84fb6b.s3.eu-west-3.amazonaws.com/property_attachment/detail_image/property_attachment_1nwsmyoyki_20240306024257.jpg', 'https://respacio-4c53102df1c9de6eca4f00689a84fb6b.s3.eu-west-3.amazonaws.com/property_attachment/detail_image/property_attachment_1db9hbpwru_20240306024310.jpg'],
    location: 'Marbella, Casco Antiguo',
    refNumber: 'EE-014',
    bedrooms: 3,
    bathrooms: 3,
    description: 'A beautifully renovated townhouse located in the heart of Marbella\'s charming Old Town. This unique property combines modern comforts with traditional Andalusian character. Features include a stunning rooftop terrace with a plunge pool and views over the old town.',
    m2: 180,
    town: 'Marbella',
    area: 'Casco Antiguo',
    propertyType: 'Townhouse',
    plotSize: 80,
    buildYear: 2021,
    terrace: true,
    aiHints: ['renovated townhouse', 'old town'],
  },
  {
    id: '15',
    title: 'Luxurious Villa with Ocean View',
    price: 2500000,
    images: ['https://fotos15.apinmo.com/7515/25945157/2-1.jpg', 'https://fotos15.apinmo.com/7515/25945157/2-2.jpg', 'https://fotos15.apinmo.com/7515/25945157/2-3.jpg'],
    location: 'Marbella, Golden Mile',
    refNumber: 'EE-015',
    bedrooms: 5,
    bathrooms: 6,
    description: 'A stunning modern villa located on the prestigious Golden Mile of Marbella. This property boasts panoramic sea views, a private infinity pool, and state-of-the-art home automation. The open-plan living space is perfect for entertaining, with floor-to-ceiling windows that flood the interior with natural light.',
    m2: 650,
    town: 'Marbella',
    area: 'Golden Mile',
    propertyType: 'Villa',
    plotSize: 1500,
    buildYear: 2022,
    terrace: true,
    aiHints: ['luxury villa', 'ocean view'],
  },
  {
    id: '16',
    title: 'Modern Apartment in the City Center',
    price: 850000,
    images: ['https://harrishomes.es/wp-content/uploads/2024/07/IMG_2376-scaled.jpeg', 'https://harrishomes.es/wp-content/uploads/2024/07/IMG_2375-scaled.jpeg'],
    location: 'Malaga, Centro Histórico',
    refNumber: 'EE-016',
    bedrooms: 3,
    bathrooms: 2,
    description: 'Chic and stylish apartment in the heart of Malaga\'s historic center. Fully renovated with high-end finishes, this property is steps away from museums, restaurants, and shops. Features a spacious living area and a private balcony overlooking the vibrant city streets.',
    m2: 180,
    town: 'Malaga',
    area: 'Centro Histórico',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2020,
    terrace: true,
    aiHints: ['modern apartment', 'city center'],
  },
  {
    id: '17',
    title: 'Charming Townhouse in a Gated Community',
    price: 650000,
    images: ['https://movr.es/media/images/properties/thumbnails/500508_xl.jpg'],
    location: 'Estepona, New Golden Mile',
    refNumber: 'EE-017',
    bedrooms: 4,
    bathrooms: 3,
    description: 'A beautiful townhouse in a quiet, family-friendly gated community. The property includes a private garden, access to a communal pool, and is just a short walk from the beach. Perfect for families or as a holiday home.',
    m2: 220,
    town: 'Estepona',
    area: 'New Golden Mile',
    propertyType: 'Townhouse',
    plotSize: 300,
    buildYear: 2018,
    terrace: true,
    aiHints: ['charming townhouse', 'gated community'],
  },
  {
    id: '18',
    title: 'Exclusive Penthouse with Rooftop Terrace',
    price: 3200000,
    images: ['https://fotos15.apinmo.com/7515/25946324/7-1.jpg', 'https://fotos15.apinmo.com/7515/25946324/7-2.jpg', 'https://fotos15.apinmo.com/7515/25946324/7-3.jpg'],
    location: 'Benahavís, La Zagaleta',
    refNumber: 'EE-018',
    bedrooms: 4,
    bathrooms: 5,
    description: 'An exquisite penthouse offering the ultimate in luxury living. The highlight is the expansive rooftop terrace with a private plunge pool, outdoor kitchen, and breathtaking 360-degree views of the mountains and the Mediterranean Sea.',
    m2: 450,
    town: 'Benahavís',
    area: 'La Zagaleta',
    propertyType: 'Penthouse',
    plotSize: 0,
    buildYear: 2021,
    terrace: true,
    aiHints: ['exclusive penthouse', 'rooftop terrace'],
  },
   {
    id: '19',
    title: 'Contemporary Villa in a Golf Resort',
    price: 1800000,
    images: ['https://fotos15.apinmo.com/7515/26122402/11-1.jpg', 'https://fotos15.apinmo.com/7515/26122402/11-2.jpg', 'https://fotos15.apinmo.com/7515/26122402/11-3.jpg'],
    location: 'Mijas, La Cala Golf',
    refNumber: 'EE-019',
    bedrooms: 4,
    bathrooms: 4,
    description: 'Sleek and modern villa located within a prestigious golf resort. This property features clean lines, open spaces, and high-quality materials. Enjoy the tranquility and stunning views of the golf course from your private terrace and pool.',
    m2: 500,
    town: 'Mijas',
    area: 'La Cala Golf',
    propertyType: 'Villa',
    plotSize: 1200,
    buildYear: 2023,
    terrace: true,
    aiHints: ['contemporary villa', 'golf resort'],
  },
  {
    id: '20',
    title: 'Beachfront Apartment with Direct Access',
    price: 1100000,
    images: ['https://www.selenhome.com/objetos/temp/source/selenhome/697253/Screenshot_10.jpeg', 'https://www.selenhome.com/objetos/temp/source/selenhome/697253/Screenshot_60.jpeg'],
    location: 'Fuengirola, Los Boliches',
    refNumber: 'EE-020',
    bedrooms: 2,
    bathrooms: 2,
    description: 'A rare opportunity to own a frontline beach apartment with direct access to the sand. Wake up to the sound of the waves and enjoy stunning sunrises from your private balcony. The community offers a large swimming pool and well-maintained gardens.',
    m2: 150,
    town: 'Fuengirola',
    area: 'Los Boliches',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2015,
    terrace: true,
    aiHints: ['beachfront apartment', 'sea view'],
  },
  {
    id: '21',
    title: 'Modern Townhouse with Solarium',
    price: 750000,
    images: ['https://www.selenhome.com/objetos/temp/source/selenhome/729643/Screenshot_1.jpeg'],
    location: 'San Pedro de Alcántara',
    refNumber: 'EE-021',
    bedrooms: 3,
    bathrooms: 3,
    description: 'Brand new townhouse in a contemporary development. Features a spacious solarium with a jacuzzi, perfect for enjoying the Spanish sun. Located close to the town center and a short drive to Puerto Banús.',
    m2: 190,
    town: 'San Pedro',
    area: 'Centro',
    propertyType: 'Townhouse',
    plotSize: 150,
    buildYear: 2024,
    terrace: true,
    aiHints: ['modern townhouse', 'solarium'],
  },
  {
    id: '22',
    title: 'Luxury Villa with Sea View',
    price: 2800000,
    images: ['https://fotos15.apinmo.com/7515/26049997/9-1.jpg', 'https://fotos15.apinmo.com/7515/26049997/9-2.jpg', 'https://fotos15.apinmo.com/7515/26049997/9-3.jpg'],
    location: 'Marbella, Sierra Blanca',
    refNumber: 'EE-022',
    bedrooms: 6,
    bathrooms: 7,
    description: 'An imposing villa in the sought-after Sierra Blanca urbanisation, offering breathtaking sea views. This property combines classic Andalusian architecture with modern luxury, featuring a home cinema, gym, and a large tropical garden.',
    m2: 800,
    town: 'Marbella',
    area: 'Sierra Blanca',
    propertyType: 'Villa',
    plotSize: 2000,
    buildYear: 2019,
    terrace: true,
    aiHints: ['luxury villa', 'sea view'],
  },
  {
    id: '23',
    title: 'Luxurious Villa with Ocean View',
    price: 2500000,
    images: ['https://members.alphashare.com/photos/full_1376071_62493848.jpg', 'https://members.alphashare.com/photos/full_1376071_62493861.jpg', 'https://members.alphashare.com/photos/full_1376071_62493872.jpg'],
    location: 'Marbella, Golden Mile',
    refNumber: 'EE-023',
    bedrooms: 5,
    bathrooms: 6,
    description: 'A stunning modern villa located on the prestigious Golden Mile of Marbella. This property boasts panoramic sea views, a private infinity pool, and state-of-the-art home automation. The open-plan living space is perfect for entertaining, with floor-to-ceiling windows that flood the interior with natural light.',
    m2: 650,
    town: 'Marbella',
    area: 'Golden Mile',
    propertyType: 'Villa',
    plotSize: 1500,
    buildYear: 2022,
    terrace: true,
    aiHints: ['luxury villa', 'ocean view'],
  },
  {
    id: '24',
    title: 'Modern Apartment in the City Center',
    price: 850000,
    images: ['https://fotos15.apinmo.com/5000/26138530/4-1.jpg', 'https://fotos15.apinmo.com/5000/26138530/4-2.jpg'],
    location: 'Malaga, Centro Histórico',
    refNumber: 'EE-024',
    bedrooms: 3,
    bathrooms: 2,
    description: 'Chic and stylish apartment in the heart of Malaga\'s historic center. Fully renovated with high-end finishes, this property is steps away from museums, restaurants, and shops. Features a spacious living area and a private balcony overlooking the vibrant city streets.',
    m2: 180,
    town: 'Malaga',
    area: 'Centro Histórico',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2020,
    terrace: true,
    aiHints: ['modern apartment', 'city center'],
  },
  {
    id: '25',
    title: 'Charming Townhouse in a Gated Community',
    price: 650000,
    images: ['https://costagroupestates.com/media/images/properties/o_1in2f5o7h1kl51hqqkdlk8gqu536.jpg'],
    location: 'Estepona, New Golden Mile',
    refNumber: 'EE-025',
    bedrooms: 4,
    bathrooms: 3,
    description: 'A beautiful townhouse in a quiet, family-friendly gated community. The property includes a private garden, access to a communal pool, and is just a short walk from the beach. Perfect for families or as a holiday home.',
    m2: 220,
    town: 'Estepona',
    area: 'New Golden Mile',
    propertyType: 'Townhouse',
    plotSize: 300,
    buildYear: 2018,
    terrace: true,
    aiHints: ['charming townhouse', 'gated community'],
  },
  {
    id: '26',
    title: 'Exclusive Penthouse with Rooftop Terrace',
    price: 3200000,
    images: ['https://images.optima-crm.com//resize/commercial_images/67a9cdf076f10822407b77e9/1200/20250210133323000000_Nicky-Winston--10.jpg', 'https://images.optima-crm.com//resize/commercial_images/67a9cdf076f10822407b77e9/1200/20250210133322000000_Nicky-Winston--14.jpg', 'https://images.optima-crm.com//resize/commercial_images/67a9cdf076f10822407b77e9/1200/20250210133317000000_Nicky-Winston--20.jpg'],
    location: 'Benahavís, La Zagaleta',
    refNumber: 'EE-026',
    bedrooms: 4,
    bathrooms: 5,
    description: 'An exquisite penthouse offering the ultimate in luxury living. The highlight is the expansive rooftop terrace with a private plunge pool, outdoor kitchen, and breathtaking 360-degree views of the mountains and the Mediterranean Sea.',
    m2: 450,
    town: 'Benahavís',
    area: 'La Zagaleta',
    propertyType: 'Penthouse',
    plotSize: 0,
    buildYear: 2021,
    terrace: true,
    aiHints: ['exclusive penthouse', 'rooftop terrace'],
  },
   {
    id: '27',
    title: 'Contemporary Villa with Pool in a Golf Resort',
    price: 1800000,
    images: ['https://www.selenhome.com/objetos/temp/source/selenhome/659383/Screenshot_2.jpeg', 'https://www.selenhome.com/objetos/temp/source/selenhome/659383/Screenshot_5.jpeg', 'https://www.selenhome.com/objetos/temp/source/selenhome/659383/Screenshot_3.jpeg'],
    location: 'Mijas, La Cala Golf',
    refNumber: 'EE-027',
    bedrooms: 4,
    bathrooms: 4,
    description: 'Sleek and modern villa located within a prestigious golf resort. This property features clean lines, open spaces, and high-quality materials. Enjoy the tranquility and stunning views of the golf course from your private terrace and pool.',
    m2: 500,
    town: 'Mijas',
    area: 'La Cala Golf',
    propertyType: 'Villa',
    plotSize: 1200,
    buildYear: 2023,
    terrace: true,
    aiHints: ['contemporary villa', 'golf resort'],
  },
  {
    id: '28',
    title: 'Beachfront Apartment with Direct Access',
    price: 1100000,
    images: ['https://images.optima-crm.com//resize/commercial_images/65c21a0eaef95f5b3fafe719/1200/20240206124516000000_CAsa-Blanca--49.jpg', 'https://images.optima-crm.com//resize/commercial_images/65c21a0eaef95f5b3fafe719/1200/20240206124342000000_CAsa-Blanca--25.jpg'],
    location: 'Fuengirola, Los Boliches',
    refNumber: 'EE-028',
    bedrooms: 2,
    bathrooms: 2,
    description: 'A rare opportunity to own a frontline beach apartment with direct access to the sand. Wake up to the sound of the waves and enjoy stunning sunrises from your private balcony. The community offers a large swimming pool and well-maintained gardens.',
    m2: 150,
    town: 'Fuengirola',
    area: 'Los Boliches',
    propertyType: 'Apartment',
    plotSize: 0,
    buildYear: 2015,
    terrace: true,
    aiHints: ['beachfront apartment', 'sea view'],
  },
  {
    id: '29',
    title: 'Modern Townhouse with Solarium',
    price: 750000,
    images: ['https://www.selenhome.com/objetos/temp/source/selenhome/576606/Image14.jpeg'],
    location: 'San Pedro de Alcántara',
    refNumber: 'EE-029',
    bedrooms: 3,
    bathrooms: 3,
    description: 'Brand new townhouse in a contemporary development. Features a spacious solarium with a jacuzzi, perfect for enjoying the Spanish sun. Located close to the town center and a short drive to Puerto Banús.',
    m2: 190,
    town: 'San Pedro',
    area: 'Centro',
    propertyType: 'Townhouse',
    plotSize: 150,
    buildYear: 2024,
    terrace: true,
    aiHints: ['modern townhouse', 'solarium'],
  },
  {
    id: '30',
    title: 'Luxury Villa with Sea View',
    price: 2800000,
    images: ['https://www.selenhome.com/objetos/temp/source/selenhome/571054/Screenshot_122314.jpeg', 'https://www.selenhome.com/objetos/temp/source/selenhome/571054/Screenshot_122313.jpeg', 'https://www.selenhome.com/objetos/temp/source/selenhome/571054/Screenshot_122312.jpeg'],
    location: 'Marbella, Sierra Blanca',
    refNumber: 'EE-030',
    bedrooms: 6,
    bathrooms: 7,
    description: 'An imposing villa in the sought-after Sierra Blanca urbanisation, offering breathtaking sea views. This property combines classic Andalusian architecture with modern luxury, featuring a home cinema, gym, and a large tropical garden.',
    m2: 800,
    town: 'Marbella',
    area: 'Sierra Blanca',
    propertyType: 'Villa',
    plotSize: 2000,
    buildYear: 2019,
    terrace: true,
    aiHints: ['luxury villa', 'sea view'],
  }
];

export const getPropertyById = (id: string | number) => {
  return properties.find(property => property.id === String(id));
};
